ALTER TABLE world ADD COLUMN slug text NOT NULL DEFAULT 'exilium-prime';
ALTER TABLE world ADD CONSTRAINT world_slug_key UNIQUE (slug);
ALTER TABLE world ADD CONSTRAINT world_slug_check CHECK (slug = 'exilium-prime');

ALTER TABLE players ALTER COLUMN token_hash DROP NOT NULL;
ALTER TABLE players ADD COLUMN handle text;
ALTER TABLE players ADD COLUMN password_hash text;
ALTER TABLE players ADD CONSTRAINT players_handle_key UNIQUE (handle);
ALTER TABLE players ADD CONSTRAINT players_handle_check
    CHECK (handle IS NULL OR handle ~ '^[a-z0-9_]{3,32}$');
ALTER TABLE players ADD CONSTRAINT players_credentials_check
    CHECK ((handle IS NULL) = (password_hash IS NULL));

CREATE TABLE auth_sessions (
    id uuid PRIMARY KEY,
    player_id uuid NOT NULL REFERENCES players(id),
    token_hash text NOT NULL UNIQUE CHECK (length(token_hash) = 64),
    created_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL CHECK (expires_at > created_at),
    revoked_at timestamptz CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);
CREATE INDEX auth_sessions_active ON auth_sessions(token_hash) WHERE revoked_at IS NULL;

CREATE TABLE world_memberships (
    world_id smallint NOT NULL REFERENCES world(id),
    player_id uuid NOT NULL REFERENCES players(id),
    joined_at timestamptz NOT NULL,
    PRIMARY KEY (world_id, player_id)
);

CREATE TABLE world_cells (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    world_id smallint NOT NULL REFERENCES world(id),
    q integer NOT NULL,
    r integer NOT NULL,
    terrain text NOT NULL CHECK (terrain IN ('plain', 'ridge', 'crater')),
    buildable boolean NOT NULL,
    UNIQUE (world_id, q, r)
);
INSERT INTO world_cells(id, world_id, q, r, terrain, buildable) VALUES
    (1, 1, -1, -1, 'ridge', true), (2, 1, 0, -1, 'plain', true),
    (3, 1, 1, -1, 'crater', false), (4, 1, -1, 0, 'plain', true),
    (5, 1, 0, 0, 'crater', false), (6, 1, 1, 0, 'plain', true),
    (7, 1, -1, 1, 'ridge', true), (8, 1, 0, 1, 'plain', true),
    (9, 1, 1, 1, 'ridge', true);
SELECT setval(pg_get_serial_sequence('world_cells', 'id'), 9, true);

ALTER TABLE cities DROP CONSTRAINT cities_owner_id_key;
ALTER TABLE cities ADD COLUMN cell_id bigint UNIQUE REFERENCES world_cells(id);
ALTER TABLE cities ADD COLUMN is_capital boolean NOT NULL DEFAULT false;
CREATE UNIQUE INDEX cities_one_capital_per_owner ON cities(owner_id) WHERE is_capital;

CREATE FUNCTION validate_city_cell() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE cell_world smallint;
DECLARE can_build boolean;
BEGIN
    IF NEW.cell_id IS NULL THEN
        RETURN NEW;
    END IF;
    SELECT world_id, buildable INTO cell_world, can_build
    FROM world_cells WHERE id = NEW.cell_id FOR UPDATE;
    IF NOT FOUND OR NOT can_build OR cell_world <> NEW.world_id THEN
        RAISE EXCEPTION 'invalid colony cell' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TRIGGER city_cell_valid BEFORE INSERT OR UPDATE OF cell_id, world_id ON cities
FOR EACH ROW EXECUTE FUNCTION validate_city_cell();

CREATE TABLE idempotency_records (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    player_id uuid NOT NULL REFERENCES players(id),
    idempotency_key uuid NOT NULL,
    action_kind text NOT NULL CHECK (action_kind IN ('found_colony', 'build_extractor', 'strategic_order')),
    payload_hash text NOT NULL CHECK (length(payload_hash) = 64),
    result jsonb NOT NULL,
    created_at timestamptz NOT NULL,
    UNIQUE (player_id, idempotency_key)
);
CREATE TRIGGER idempotency_immutable BEFORE UPDATE OR DELETE OR TRUNCATE ON idempotency_records
FOR EACH STATEMENT EXECUTE FUNCTION reject_audit_mutation();

CREATE TABLE city_buildings (
    id uuid PRIMARY KEY,
    city_id uuid NOT NULL REFERENCES cities(id),
    kind text NOT NULL CHECK (kind = 'extractor'),
    built_at timestamptz NOT NULL,
    action_id bigint NOT NULL UNIQUE REFERENCES idempotency_records(id)
);
CREATE INDEX city_buildings_city ON city_buildings(city_id, kind);

ALTER TABLE resource_ledger DROP CONSTRAINT resource_ledger_reason_check;
ALTER TABLE resource_ledger DROP CONSTRAINT resource_ledger_check;
ALTER TABLE resource_ledger ADD CONSTRAINT resource_ledger_reason_check
    CHECK (reason IN ('genesis', 'production', 'upgrade', 'extractor'));
ALTER TABLE resource_ledger ADD CONSTRAINT resource_ledger_sign_check
    CHECK ((reason IN ('genesis', 'production') AND amount > 0) OR
           (reason IN ('upgrade', 'extractor') AND amount < 0));
